import { PRODUCT_API_BASE } from "../config";
import { apiRequest } from "./client";

// Matches product-services/src/models/products.js exactly.
export interface ApiProduct {
  _id?: string;
  productID: string;
  category: string;
  collection: string;
  metal: string;
  name: string;
  description: string;
  // Computed live by the backend from weight + metal + current gold/silver
  // rate on every request — not stored in the DB. Never send this back.
  price: number;
  weight: number;
  stock: number;
  image?: string;
  images?: string[];
  certification?: string;
  createdAt: string;
}

export interface NewProductPayload {
  name: string;
  category: string;
  collection: string;
  metal: string;
  description: string;
  weight: number;
  stock: number;
  image?: string;
  images?: string[];
  certification?: string;
}

interface GetProductsResponse {
  message: string;
  products: {
    totalproducts: number;
    products: ApiProduct[];
  };
}

interface AddProductResponse {
  message: string;
  product: ApiProduct;
}

// GET / - public route, but we're already authenticated as admin so it's fine either way
export const fetchProducts = async (): Promise<ApiProduct[]> => {
  const data = await apiRequest<GetProductsResponse>(`${PRODUCT_API_BASE}/`);
  return data.products.products;
};

// Reads the file directly in the browser and returns a base64 data URL.
// Used as a fallback so a product photo is never lost even if the
// /upload-image route on the backend is unavailable or misbehaves.
const readFileAsDataURL = (file: File): Promise<string> =>
  new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = () => reject(new Error("Could not read image file"));
    reader.readAsDataURL(file);
  });

export const uploadProductImage = async (file: File): Promise<string> => {
  const formData = new FormData();
  formData.append("image", file);

  const token = localStorage.getItem("hiranya_admin_token");

  try {
    const response = await fetch(`${PRODUCT_API_BASE}/upload-image`, {
      method: "POST",
      headers: token ? { Authorization: `Bearer ${token}` } : undefined,
      body: formData, // no Content-Type header — browser sets the multipart boundary
    });

    // If the backend didn't return JSON (e.g. an HTML error page), don't
    // call response.json() — that's what throws "Unexpected token '<'".
    const contentType = response.headers.get("content-type") || "";
    if (!contentType.includes("application/json")) {
      return await readFileAsDataURL(file);
    }

    const data = await response.json();
    if (!response.ok) {
      throw new Error(data?.message || "Image upload failed");
    }
    return data.url; // backend returns the hosted URL
  } catch {
    // Network error, backend down, or bad response — fall back to a local
    // data URL so the admin can still preview + save the photo.
    return readFileAsDataURL(file);
  }
};

// POST /add - protected by authMiddleware + adminMiddleware
export const addProduct = async (
  payload: NewProductPayload
): Promise<ApiProduct> => {
  // productID is auto-generated by the backend — never sent from the client.
  const data = await apiRequest<AddProductResponse>(
    `${PRODUCT_API_BASE}/add`,
    {
      method: "POST",
      body: payload,
    }
  );
  return data.product;
};

interface DeleteProductResponse {
  message: string;
  product: ApiProduct;
}

// DELETE /delete/:productID - protected by authMiddleware + adminMiddleware
export const deleteProduct = async (productID: string): Promise<void> => {
  await apiRequest<DeleteProductResponse>(
    `${PRODUCT_API_BASE}/delete/${productID}`,
    { method: "DELETE" }
  );
};

// All fields optional — only send what changed.
export type UpdateProductPayload = Partial<NewProductPayload>;

interface UpdateProductResponse {
  message: string;
  product: ApiProduct;
}

// PATCH /update/:productID - protected by authMiddleware + adminMiddleware
export const updateProduct = async (
  productID: string,
  payload: UpdateProductPayload
): Promise<ApiProduct> => {
  const data = await apiRequest<UpdateProductResponse>(
    `${PRODUCT_API_BASE}/update/${productID}`,
    {
      method: "PATCH",
      body: payload,
    }
  );
  return data.product;
};
