import mongoose from "mongoose";

const customDesignSchema = new mongoose.Schema(
  {
    // ================= USER =================
    userId: {
      type: String,
      required: true,
      index: true,
    },

    // ================= CUSTOM ORDER ID =================
    // Human-friendly identifier generated by the backend (see
    // utils/helpers.js -> generateCustomOrderId) so every submission can be
    // told apart from every other one, e.g. "CD00001". Assigned once, on
    // creation, in the controller - never set by the client.
    customOrderId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },

    // ================= CUSTOMER =================
    customer: {
      fullName: {
        type: String,
        required: true,
      },
      email: {
        type: String,
        required: true,
      },
      phone: {
        type: String,
        required: true,
      },
      address: {
        type: String,
        default: "",
      },
    },

    // ================= JEWELLERY =================
    jewellery: {
      type: {
        type: String,
        required: true,
      },
      material: {
        type: String,
        required: true,
      },
      purity: {
        type: String,
        required: true,
      },
      gemstone: [
        {
          name: {
            type: String,
            required: true,
          },
          quantity: {
            type: Number,
            required: true,
            min: 0,
          },
        },
      ],
      // Quality/clarity grade (0-100) applied across the selected
      // gemstones — mirrors the metal `purity` field above, but for
      // stones. See client PuritySelector-style slider in GemstoneSelector.
      gemstonePurity: {
        type: Number,
        min: 0,
        max: 100,
        default: 50,
      },
      style: {
        type: String,
        default: "",
      },
    },

    // ================= BUDGET =================
    budget: {
      min: {
        type: Number,
        required: true,
        min: 0,
      },
      max: {
        type: Number,
        required: true,
        min: 0,
      },
      estimatedPrice: {
        type: Number,
        default: 0,
      },
    },

    // ================= DESIGN =================
    design: {
      description: {
        type: String,
        default: "",
      },
      referenceImages: [
        {
          type: String,
        },
      ],
    },

    // ================= ESTIMATION =================
    estimation: {
      makingCharge: {
        type: Number,
        default: 0,
      },
      stoneCost: {
        type: Number,
        default: 0,
      },
      metalCost: {
        type: Number,
        default: 0,
      },
      totalEstimatedCost: {
        type: Number,
        default: 0,
      },
    },

    // ================= PAYMENT =================
    payment: {
      paymentStatus: {
        type: String,
        enum: ["Pending", "Paid", "Failed", "Refunded"],
        default: "Pending",
      },
    },

    // ================= ORDER STATUS =================
    orderStatus: {
      type: String,
      enum: [
        "Pending",
        "Design Review",
        "Approved",
        "In Production",
        "Ready",
        "Completed",
        "Cancelled",
      ],
      default: "Pending",
    },

    // ================= ADMIN NOTES =================
    // Not part of the base schema spec, but relied on by the admin
    // dashboard's "Note to customer" field and the customer-facing
    // "My Custom Orders" page, so it's kept as an additional field.
    adminNotes: {
      type: String,
      default: "",
    },

    // ================= CHAT =================
    // Chat thread between the customer and admin about this specific
    // custom design request. Powers the "My Custom Orders" chat on the
    // customer side and the Custom Design tab reply box in the admin
    // dashboard. Kept as an additional field alongside the base schema.
    messages: [
      {
        sender: {
          type: String,
          enum: ["customer", "admin"],
          required: true,
        },
        text: {
          type: String,
          required: true,
          trim: true,
        },
        createdAt: {
          type: Date,
          default: Date.now,
        },
      },
    ],
  },
  {
    timestamps: true,
  }
);

export default mongoose.model("CustomDesign", customDesignSchema);
